clean test

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -124,12 +124,12 @@ jobs:
       if: needs.rebuild.outputs.updated == 'true'
       run: sleep 60
 
-    - uses: actions/checkout@v6
-
-    - name: install python
-      uses: actions/setup-python@v6
-      with:
-        python-version: '3.12'
+#    - uses: actions/checkout@v6
+#
+#    - name: install python
+#      uses: actions/setup-python@v6
+#      with:
+#        python-version: '3.12'
 
     - name: install apt repo
       run: |
@@ -149,7 +149,43 @@ jobs:
         sudo apt -y install desktop-file-utils zotero zotero-beta xvfb libegl1 libgl1 libdbus-glib-1-2
         dpkg -l | grep zotero
 
-        for c in zotero zotero-beta; do
-          ./start.py $c
-          desktop-file-validate /usr/share/applications/$c.desktop && echo 'all clear!'
+    - name: test all the things
+      run: |
+        set -eu
+
+        for Z in zotero zotero-beta; do
+          rm -f $Z.log
+
+          echo "starting $Z"
+
+          xvfb-run --server-args="-screen 0 1024x768x24" /usr/lib/$Z/zotero -ZoteroDebugText > $Z.log 2>&1 &
+  
+          PID=$!
+          echo "started $Z (pid $PID)"
+
+          sleep 20
+          echo "  stopping $Z"
+  
+          kill -TERM -$PID 2>/dev/null || true
+          sleep 5
+
+          kill -0 $PID 2>/dev/null && { 
+            echo "  !! killing $Z"
+            kill -KILL -$PID 2>/dev/null || true
+          }
+
+          wait $PID 2>/dev/null || true
+
+          grep -q "Asynchronously opening database" $Z.log || {
+            echo "  $Z failed to start correctly"
+            cat $Z.log
+            exit 1
+          }
+
+          echo "  $Z started normally"
         done
+
+#        for c in zotero zotero-beta; do
+#          ./start.py $c
+#          desktop-file-validate /usr/share/applications/$c.desktop && echo 'all clear!'
+#        done
